# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform, QDoubleValidator, QIntValidator)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QMainWindow, QPushButton, QRadioButton, QScrollArea,
    QSizePolicy, QSlider, QStatusBar, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1080, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1080, 720))
        MainWindow.setMaximumSize(QSize(1920, 1080))
        MainWindow.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btnCargar = QPushButton(self.centralwidget)
        self.btnCargar.setObjectName(u"btnCargar")
        self.btnCargar.setGeometry(QRect(920, 500, 111, 24))
        self.btnCargar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon = QIcon()
        icon.addFile(u"../assets/upload.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnCargar.setIcon(icon)
        self.btnGrabar = QPushButton(self.centralwidget)
        self.btnGrabar.setObjectName(u"btnGrabar")
        self.btnGrabar.setGeometry(QRect(40, 500, 75, 24))
        self.btnGrabar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u"../assets/microphone_fill.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnGrabar.setIcon(icon1)
        self.btnGrabar.setIconSize(QSize(24, 16))
        self.btnReproducir = QPushButton(self.centralwidget)
        self.btnReproducir.setObjectName(u"btnReproducir")
        self.btnReproducir.setGeometry(QRect(120, 500, 91, 24))
        self.btnReproducir.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u"../assets/play.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnReproducir.setIcon(icon2)
        self.btnGuardar = QPushButton(self.centralwidget)
        self.btnGuardar.setObjectName(u"btnGuardar")
        self.btnGuardar.setGeometry(QRect(820, 500, 91, 23))
        self.btnGuardar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnGuardar.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon3 = QIcon()
        icon3.addFile(u"../assets/folder.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnGuardar.setIcon(icon3)
        self.btnGuardar.setIconSize(QSize(16, 16))
        self.btnAnalizar = QPushButton(self.centralwidget)
        self.btnAnalizar.setObjectName(u"btnAnalizar")
        self.btnAnalizar.setGeometry(QRect(320, 500, 75, 24))
        self.btnAnalizar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnAnalizar.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon4 = QIcon()
        icon4.addFile(u"../assets/waves-left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnAnalizar.setIcon(icon4)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(40, 130, 991, 360))
        self.scrollArea.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 989, 358))
        self.scrollAreaWidgetContents.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.scrollAreaWidgetContents.setAutoFillBackground(True)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lblTitulo = QLabel(self.centralwidget)
        self.lblTitulo.setObjectName(u"lblTitulo")
        self.lblTitulo.setGeometry(QRect(100, 0, 881, 41))
        font = QFont()
        font.setPointSize(24)
        self.lblTitulo.setFont(font)
        self.btnGenerarTono = QPushButton(self.centralwidget)
        self.btnGenerarTono.setObjectName(u"btnGenerarTono")
        self.btnGenerarTono.setEnabled(True)
        self.btnGenerarTono.setGeometry(QRect(10, 570, 91, 24))
        self.btnGenerarTono.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.gbControles = QGroupBox(self.centralwidget)
        self.gbControles.setObjectName(u"gbControles")
        self.gbControles.setEnabled(False)
        self.gbControles.setGeometry(QRect(10, 600, 581, 91))
        self.gbControles.setChecked(False)
        self.gbtnCancelarTono = QPushButton(self.gbControles)
        self.gbtnCancelarTono.setObjectName(u"gbtnCancelarTono")
        self.gbtnCancelarTono.setGeometry(QRect(480, 60, 91, 24))
        self.gbtnCancelarTono.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.lblFrecuencia = QLabel(self.gbControles)
        self.lblFrecuencia.setObjectName(u"lblFrecuencia")
        self.lblFrecuencia.setGeometry(QRect(10, 20, 91, 16))
        self.gbTipoFuncion = QGroupBox(self.gbControles)
        self.gbTipoFuncion.setObjectName(u"gbTipoFuncion")
        self.gbTipoFuncion.setGeometry(QRect(400, 10, 171, 41))
        self.gbTipoFuncion.setFlat(False)
        self.gbTipoFuncion.setCheckable(False)
        self.grbSeno = QRadioButton(self.gbTipoFuncion)
        self.grbSeno.setObjectName(u"grbSeno")
        self.grbSeno.setGeometry(QRect(10, 10, 61, 20))
        self.grbSeno.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.grbCoseno = QRadioButton(self.gbTipoFuncion)
        self.grbCoseno.setObjectName(u"grbCoseno")
        self.grbCoseno.setGeometry(QRect(90, 10, 71, 20))
        self.grbCoseno.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.grbCoseno.setCheckable(True)
        self.grbCoseno.setChecked(False)
        self.grbCoseno.setAutoRepeat(False)
        self.grbCoseno.setAutoExclusive(True)
        self.lblAmplitud = QLabel(self.gbControles)
        self.lblAmplitud.setObjectName(u"lblAmplitud")
        self.lblAmplitud.setGeometry(QRect(170, 20, 61, 16))
        self.sldAmplitud = QSlider(self.gbControles)
        self.sldAmplitud.setObjectName(u"sldAmplitud")
        self.sldAmplitud.setGeometry(QRect(230, 20, 160, 22))
        self.sldAmplitud.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.sldAmplitud.setMaximum(100)
        self.sldAmplitud.setSingleStep(1)
        self.sldAmplitud.setPageStep(10)
        self.sldAmplitud.setValue(0)
        self.sldAmplitud.setTracking(True)
        self.sldAmplitud.setOrientation(Qt.Orientation.Horizontal)
        self.sldAmplitud.setInvertedAppearance(False)
        self.sldAmplitud.setInvertedControls(False)
        self.sldAmplitud.setTickPosition(QSlider.TickPosition.TicksBothSides)
        self.sldAmplitud.setTickInterval(0)
        self.gbtnDetener = QPushButton(self.gbControles)
        self.gbtnDetener.setObjectName(u"gbtnDetener")
        self.gbtnDetener.setGeometry(QRect(90, 60, 75, 24))
        self.gbtnDetener.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u"../assets/stop.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.gbtnDetener.setIcon(icon5)
        self.txtFrecuencia = QLineEdit(self.gbControles)
        self.txtFrecuencia.setObjectName(u"txtFrecuencia")
        self.txtFrecuencia.setGeometry(QRect(100, 20, 61, 22))
        validator = QIntValidator(20, 200000)
        self.txtFrecuencia.setValidator(validator)
        self.gbtnReproducir = QPushButton(self.gbControles)
        self.gbtnReproducir.setObjectName(u"gbtnReproducir")
        self.gbtnReproducir.setGeometry(QRect(10, 60, 75, 24))
        self.gbtnReproducir.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u"../assets/play.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.gbtnReproducir.setIcon(icon6)
        self.btnDetener = QPushButton(self.centralwidget)
        self.btnDetener.setObjectName(u"btnDetener")
        self.btnDetener.setGeometry(QRect(220, 500, 91, 24))
        self.btnDetener.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u"../assets/stop.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnDetener.setIcon(icon7)
        self.lblInfoArchivo = QLabel(self.centralwidget)
        self.lblInfoArchivo.setObjectName(u"lblInfoArchivo")
        self.lblInfoArchivo.setEnabled(True)
        self.lblInfoArchivo.setGeometry(QRect(40, 80, 371, 41))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Lenguaje del Sonido", None))
        self.btnCargar.setText(QCoreApplication.translate("MainWindow", u"Cargar Archivo", None))
        self.btnGrabar.setText(QCoreApplication.translate("MainWindow", u"Grabar", None))
        self.btnReproducir.setText(QCoreApplication.translate("MainWindow", u"Reproducir", None))
        self.btnGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
        self.btnAnalizar.setText(QCoreApplication.translate("MainWindow", u"Analizar", None))
        self.lblTitulo.setText(QCoreApplication.translate("MainWindow", u"El Lenguaje del Sonido: Creaci\u00f3n y An\u00e1lisis de Ondas Sonoras\n"
"", None))
        self.btnGenerarTono.setText(QCoreApplication.translate("MainWindow", u"Generar Tono", None))
        self.gbControles.setTitle(QCoreApplication.translate("MainWindow", u"Controles", None))
        self.gbtnCancelarTono.setText(QCoreApplication.translate("MainWindow", u"Cancelar Tono", None))
        self.lblFrecuencia.setText(QCoreApplication.translate("MainWindow", u"Frecuencia (Hz):", None))
        self.gbTipoFuncion.setTitle("")
        self.grbSeno.setText(QCoreApplication.translate("MainWindow", u"Seno", None))
        self.grbCoseno.setText(QCoreApplication.translate("MainWindow", u"Coseno", None))
        self.lblAmplitud.setText(QCoreApplication.translate("MainWindow", u"Amplitud:", None))
        self.gbtnDetener.setText("")
        self.gbtnReproducir.setText("")
        self.btnDetener.setText(QCoreApplication.translate("MainWindow", u"Detener", None))
        self.lblInfoArchivo.setText("")
    # retranslateUi

